config/routes.rb
Rails.application.routes.draw do
  root 'general#welcome'
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  resources :acts
  get 'contracts/:id/details' => 'contracts#contract_detail'
  resources :contracts do
    resources :documents, only: [:new, :create, :edit, :update, :destroy, :show], as: :documents
  end
  get '/performances/list' => 'performances#performances_listing'
  resources :performances
  get 'performances/:id/details' => 'performances#performance_detail'
  scope 'admin' do
    resources :users, only: [:index, :edit, :update, :destroy]
  end

  resources :venues

  post 'approvals/approve' => 'approvals#approve', as: :contract_apvl_approve
  post 'approvals/reject' => 'approvals#reject', as: :contract_apvl_reject
  post 'approvals/cancel' => 'approvals#cancel', as: :contract_apvl_cancel
  get  'approvals/pending' => 'approvals#pending_approval'


end

app/models/approval.rb
class Approval < ActiveRecord::Base
  belongs_to :contract
  belongs_to :user

  validates_presence_of :status

  def mark_approved
    self.status = "approved"
    self.date_answered = Time.now
    self.save
  end

  def mark_cancelled
    self.status = "cancelled"
    self.date_answered = Time.now
    self.save
  end

  def mark_rejected
    self.status = "rejected"
    self.date_answered = Time.now
    self.save
  end

  def self.pending_approval
    self.where(status: "pending")
  end

end

app/controllers/approvals_controller.rb
class ApprovalsController < ApplicationController
  before_action :get_approval, only: [:approve, :cancel, :reject, :destroy]

  def approve
    if @approval && (@approval.user_id == current_user.id || current_user.is_admin)
      if @approval.mark_approved
        render json: @approval, status: 201
      else
        render status: 400
      end
    else
      render status: 401
    end
  end

  def reject
    if @approval && (@approval.user_id == current_user.id)
      if @approval.mark_rejected
        render json: @approval, status: 201
      else
        render status: 400
      end
    else
      render status: 401
    end
  end

  def cancel
    if @approval && current_user.is_admin
      if @approval.mark_cancelled
        render json: @approval, status: 201
      else
        render status: 400
      end
    else
      render status: 401
    end
  end


  def pending_approval
    authorize @approvals = Approval.pending_approval
  end

  private
  def get_approval
    authorize @approval = Approval.find_by(id: params[:id])
  end
end

app/views/approvals/_approval.html.erb
<tr>
  <td class="col-md-2"><%= approval.contract.performance.name %> <%= link_to "#{icon('arrow-circle-right')}".html_safe, contract_path(approval.contract) %></td>
  <td><%= approval.contract.performance.act.name %>  <%= link_to "#{icon('arrow-circle-right')}".html_safe, act_path(approval.contract.performance.act) %></td>
  <td><%= approval.contract.performance.venue.name %> <%= link_to "#{icon('arrow-circle-right')}".html_safe, venue_path(approval.contract.performance.venue) %></td>
  <td><%= fmatdate(approval.contract.performance.perf_date) %></td>
  <td><%= "#{approval.user.name} (#{approval.user.email})" %></td>
</tr>

app/views/approvals/pending_approval.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Performance Name</th>
      <th>Act</th>
      <th>Venue</th>
      <th>Performance Date</th>
      <th>Approver</th>
    </tr>
  </thead>
  <tbody>
     <%= render(@approvals) || "<tr><td colspan='6'>No data to list</td></tr>".html_safe %>
  </tbody>
</table>