config/routes.rb
Rails.application.routes.draw do
  root 'general#welcome'
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  resources :acts
  get 'contracts/:id/details' => 'contracts#contract_detail'
  resources :contracts do
    resources :documents, only: [:new, :create, :edit, :update, :destroy, :show], as: :documents
  end
  get '/performances/list' => 'performances#performances_listing'
  resources :performances
  get 'performances/:id/details' => 'performances#performance_detail'
  scope 'admin' do
    resources :users, only: [:index, :edit, :update, :destroy]
  end

  resources :venues

  post 'approvals/approve' => 'approvals#approve', as: :contract_apvl_approve
  post 'approvals/reject' => 'approvals#reject', as: :contract_apvl_reject
  post 'approvals/cancel' => 'approvals#cancel', as: :contract_apvl_cancel
  get  'approvals/pending' => 'approvals#pending_approval'


end

app/models/contract.rb
class Contract < ActiveRecord::Base
  belongs_to :performance
  has_many :documents
  has_many :approvals

  validates_presence_of :performance_id, :status, :details
  validate :check_due_date

  def check_due_date
    if due_date < Date.today
      errors.add(:contract, "Due Date cannot be in the past.")
    end
  end

  def status_value
    if status == "pend"
      "Pending"
    elsif status == "submit"
      "Submitted"
    elsif status =="app"
       "Approved"
     elsif status == "ff"
       "Fulfilled"
     elsif status == "cancel"
       "Cancelled"
    end
  end

  def approvals_attributes=(approval_attributes)
    approval_attributes.values.each do |approval_attribute|

      if !approval_attribute[:user_id].blank?
        approval = Approval.find_or_initialize_by(approval_attribute)
        approval.status = "pending" if !approval.persisted?
        approval.save
        self.approvals << approval
      end
    end
  end

end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :get_contract, only: [:show, :edit, :update, :destroy,  :contract_detail]

  def new
    authorize @contract = Contract.new
  end

  def create
    authorize @contract = Contract.new(contract_params)
    if @contract.save
      redirect_to @contract
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @contract.update(contract_params)
      redirect_to @contract
    else
      render 'edit'
    end
  end

  def show
    @approvals = Approval.where(contract_id: @contract.id)
    @documents = Document.where(contract_id: @contract.id)
    @document = Document.new
  end

  def contract_detail
    if @contract
      render json: @contract, serializer: ContractSerializer, status: 201
    else
      render status: 400
    end
  end

  def index
    authorize @contracts = policy_scope(Contract).order(due_date: :asc)
  end

  def destroy
    @contract.delete if @contract
    redirect_to contracts_path
  end

  private
  def get_contract
    authorize @contract = Contract.find(params[:id])
  end

  def contract_params
    params.require(:contract).permit(:performance_id, :submit_date, :due_date, :status, :details, approvals_attributes: [:contract_id, :user_id, :date_requested, :date_answered, :status])
  end
end

app/views/contracts/_approval.html.erb
<tr data-approval-id="<%= approval.id %>">
  <td id="username"><%= approval.user.name %></td>
  <td id="role"><%= approval.user.role %></td>
  <td id="date_requested"><%= fmatdate(approval.date_requested) %></td>
  <td id="date_answered"> <%= fmatdate(approval.date_answered) %></td>
  <td id="status"><%= approval.status %></td>
  <td id="buttons">
    <% if approval.status == 'pending' && current_user.try(:id) == approval.user_id %>
    <div style="float: left; padding-left:10px;">
      <%= button_to contract_apvl_approve_path, class:"btn btn-success btn-sm",  form: {id: "approval", "data-approval-answer" => "approve", "data-approval-id" => approval.id} do %>
      <strong><%= icon('check') %> Approve</strong>
      <% end %>
    </div>
    <div style="float: left; padding-left:10px;">
      <%= button_to contract_apvl_reject_path, class:"btn btn-danger btn-sm", form: {id: "approval", "data-approval-answer" => "reject", "data-approval-id" => approval.id} do %>
      <strong><%= icon('times') %> Reject</strong>
      <% end %></div>
      <% end %>
      <% if approval.status == 'pending' && current_user.is_admin %>
      <div style="float: left; padding-left:10px;">
        <%= button_to contract_apvl_cancel_path, class:"btn btn-warning btn-sm", form: {id: "approval", "data-approval-answer" => "cancel", "data-approval-id" => approval.id} do %>
        <strong><%= icon('ban') %> Cancel Approval Request</strong>
        <% end %>
      </div>
      <% end %>
    </td>
  </tr>

app/views/contracts/_contract.html.erb
<tr>
  <td class="col-md-2"><%= contract.performance.name %></td>
  <td><%= contract.performance.act.name %>  <%= link_to "#{icon('arrow-circle-right')}".html_safe, act_path(contract.performance.act) %></td>
  <td><%= contract.performance.venue.name %> <%= link_to "#{icon('arrow-circle-right')}".html_safe, venue_path(contract.performance.venue) %></td>
  <td><%= fmatdate(contract.performance.perf_date) %></td><td><%= contract.status %></td>
  <td><%= render partial: "edit_links", locals: {resource: contract, text: false, displaytype: "row"} %></td>
</tr>

app/views/contracts/_form.html.erb
<%= form_for @contract do |f| %>
  <%= render partial: "shared/errors", locals: {md: @contract} %>
  <h3>Details</h3>
  <%= f.label :performance %><br />
  <%= Performance.find_by(id: (params[:performance_id] || f.object.performance_id)).try(:performance_string) %>
  <%= f.hidden_field :performance_id, {:value => (f.object.performance_id || params[:performance_id])} %>
  <br>
  <%= f.label :submit_date %>
  <%= f.date_field :submit_date, class: "form-control" %><br>
  <%= f.label :due_date %>
  <%= f.date_field :due_date, class: "form-control" %><br>
  <%= f.label :status %><br />
  <%= f.select :status, options_for_contract_status,{}, {class: 'form-control'} %><br>
  <%= f.label :details %><br>
  <%= f.text_area :details, class: "form-control", rows: 3 %>
  <h3>Add Approvers</h3>
  <%= f.fields_for :approvals, @contract.approvals.build do |f_approval| %>
    <%= f_approval.label 'User' %>
    <%= f_approval.collection_select(:user_id, User.users_for_approval_selection(@contract.performance.try(:act_id), @contract.performance.try(:venue_id)), :id, :email, {include_blank: 'Select'}, {class: "form-control"}) %><br>
    <%= f_approval.label 'Date Due' %>
    <%= f_approval.date_field :date_requested, class: "form-control" %><br>
  <% end %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/contracts/index.html.erb
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Act</th>
        <th>Venue</th>
        <th>Performance Date</th>
        <th>Status</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
       <%= render(@contracts) || "<tr><td colspan='6'>No data to list</td></tr>".html_safe %>
    </tbody>
  </table>

app/views/contracts/show.html.erb
<%= render partial: "edit_links", locals: {resource: @contract,  text: true, displaytype: "page"} %>
<h1 id="perfomance_name"></h1>
<div data-contract-id="<%= @contract.id %>" />
<p>
  <strong>Date: </strong><span id="perf_date"></span><br>
  <strong>Venue: </strong><span id="venue"></span><br>
  <strong>Act: </strong><span id="act"></span>
</p>
<p>
  <strong>Submit Date: </strong><span id="submit_date"></span><br>
  <strong>Due Date: </strong><span id="due_date"></span><br>
  <strong>Status: </strong><span id="contract_status"></span>
</p>
<p>
  <strong>Contract Details: </strong><br /><span id="contract_details"></span>
</p>
<h3>Documents</h3>
<% if policy(:contract).new? %><p><%= link_to "#{icon('file-o')} New Document".html_safe, "#", id: "new-doc"%></p><% end %>
<div class="modal fade" id="modalDocument" tabindex="-1" role="dialog" aria-labelledby="modalDocument">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modalDocTitle">New Document</h4>
      </div>
      <%= form_for [@contract, @document] do |f| %>
      <div class="modal-body">
        <%= render partial: "shared/errors", locals: {md: @document} %>
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %><br>
        <%= f.label :description %>
        <%= f.text_field :description, class: "form-control" %><br>
        <%= f.label :location %>
        <%= f.text_field :location, class: "form-control" %><br>
        <%= f.hidden_field :contract_id, value: @contract.id %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit id: "modalSubmit", class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>
<div class="panel panel-default col-sm-11">
  <table class="table">
    <thead>
      <tr>
        <th>Document</th>
        <th>Description</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody id="documents">
    </tbody>
  </table>
</div>
<h3>Approvals</h3>
<div class="panel panel-default col-sm-11">
  <table class="table">
    <thead>
      <tr>
        <th>Representative</th>
        <th>Role</th>
        <th>Date Requested</th>
        <th>Date Answered</th>
        <th>Status</th>
        <th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "approval", collection: @approvals %>
    </tbody>
  </table>
</div>