config/routes.rb
Rails.application.routes.draw do
  root 'general#welcome'
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  resources :acts
  get 'contracts/:id/details' => 'contracts#contract_detail'
  resources :contracts do
    resources :documents, only: [:new, :create, :edit, :update, :destroy, :show], as: :documents
  end
  get '/performances/list' => 'performances#performances_listing'
  resources :performances
  get 'performances/:id/details' => 'performances#performance_detail'
  scope 'admin' do
    resources :users, only: [:index, :edit, :update, :destroy]
  end

  resources :venues

  post 'approvals/approve' => 'approvals#approve', as: :contract_apvl_approve
  post 'approvals/reject' => 'approvals#reject', as: :contract_apvl_reject
  post 'approvals/cancel' => 'approvals#cancel', as: :contract_apvl_cancel
  get  'approvals/pending' => 'approvals#pending_approval'


end

app/models/performance.rb
class Performance < ActiveRecord::Base
  belongs_to :act
  belongs_to :venue
  has_one :contract
  validates_presence_of :act_id, :venue_id, :name, :description, :perf_date
  validates :tkts_url, format: { with: URI.regexp }
  validate :check_perf_date

  def check_perf_date
    if perf_date.present?
      unless perf_date >= Date.today
        errors.add(:performance, "Performance date must be in the future.")
      end
    end
  end

  def performance_string
    "#{name} - #{venue.name} - #{perf_date}"
  end

end

app/controllers/performances_controller.rb
class PerformancesController < ApplicationController
  before_action :get_performance, only: [:show, :edit, :update, :destroy, :performance_detail]

  def new
    authorize @performance = Performance.new
  end

  def create
    authorize @performance = Performance.new(performance_params)
    if @performance.save
      redirect_to @performance
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @performance.update(performance_params)
      redirect_to @performance
    else
      render 'edit'
    end
  end

  def show
  end

  def performance_detail
    if @performance
      render json: @performance, serializer: PerformanceDetailSerializer, status: 201
    else
      render status: 400
    end
  end

  def performances_listing
    authorize @performances = policy_scope(Performance).order(perf_date: :desc)

    if params[:type] == "home"
      @performances = @performances
    elsif params[:type] == "venue"
      @performances = @performances.where('venue_id = ?', params[:id])
    elsif params[:type] == "act"
      @performances = @performances.where('act_id = ?', params[:id])
    end

    if @performances
      render json: @performances, each_serializer: PerformanceListSerializer, status: 201
    else
      render status: 400
    end
  end

  def index
  end

  def destroy
    if @performance
      if authorize @performance.delete
        respond_to do |format|
          format.json {render json: {:id => @performance.id}, status: 201}
          format.html {redirect_to performances_path}

        end
      else
        render status: 400
      end
    end
  end

  private
  def get_performance
    authorize @performance = Performance.find(params[:id])
  end

  def performance_params
    params.require(:performance).permit(:act_id, :venue_id, :name, :perf_date, :perf_time, :tkts_url, :description)
  end
end

app/views/performances/_form.html.erb
<br />
    <%= form_for @performance do |f| %>
      <%= render partial: "shared/errors", locals: {md: @performance} %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %><br>
      <%= f.label :act_id %><br />
      <div class="input-group">
        <span class="input-group-addon" id="basic-addon1"><%= icon('star') %></span>
        <%= f.collection_select(:act_id, Act.all, :id, :name, {include_blank: 'Select'}, {class: "form-control"} )  %>
      </div>
      <br>
      <%= f.label :venue_id %><br />
      <div class="input-group">
        <span class="input-group-addon" id="basic-addon1"><%= icon('map-marker') %></span>
        <%= f.collection_select(:venue_id, Venue.all, :id, :name, {include_blank: 'Select'}, {class: "form-control"} )  %>
      </div>
      <br>
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control", rows: 3 %><br>
      <%= f.label 'Performance Date' %>
      <div class="input-group">
        <span class="input-group-addon" id="basic-addon1"><%= icon('calendar') %></span>
        <%= f.date_field :perf_date, class: "form-control" %>
      </div>
      <br>
      <%= f.label 'Performance Time' %>
      <div class="input-group">
        <span class="input-group-addon" id="basic-addon1"><%= icon('clock-o') %></span>
        <%= f.time_field :perf_time, class: "form-control" %>
      </div>
      <br>
      <%= f.label 'Ticketing Website' %>
      <div class="input-group">
        <span class="input-group-addon" id="basic-addon1"><%= icon('globe') %></span>
        <%= f.url_field :tkts_url, class: "form-control" %>
      </div>
      <br>
      <%= f.submit class: "btn btn-primary" %>
    <% end %>

app/views/performances/index.html.erb
<br />
<div class="panel-heading">
  <strong>Upcoming Shows</strong>
</div>
<div data-performance-all-list="true" />
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Act</th>
      <th>Venue</th>
      <th>Date</th>
      <th>Contract</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody id="upcoming_perf">
  </tbody>
</table>
<br />
<div class="panel-heading">
  <strong>Past Shows</strong>
</div>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Act</th>
      <th>Venue</th>
      <th>Date</th>
      <th>Contract</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody id="past_perf">
  </tbody>
</table>

app/views/performances/show.html.erb
<%= render partial: "edit_links", locals: {resource: @performance, text: true, displaytype: "page"} %>
<div data-performance-id="<%= @performance.id %>" />
<h1 id='perf_name'></h1>
<p>
  <% if @performance.try(:contract) %>
  <%= link_to "#{icon('file-text-o')} View Contract".html_safe, contract_path(@performance.contract) %>
  <% else %>
  <% if policy(:contract).new? %>
  <%= link_to "#{icon('file-text-o')} Create Contract".html_safe, new_contract_path(:performance_id => @performance.id) %>
  <% end %>
  <% end %>
</p>
<p id="date_time"><strong>Date: </strong><span id="date"></span> | <strong>Time: </strong><span id="time"></span></p>
<p id="act"><strong>Act: </strong></p>
<p id="venue"><strong>Venue: </strong></p>
<p id="description"><strong>Description: </strong><br /></p>
<p id="tickets"><strong>Ticketing: </strong></p>