config/routes.rb
Rails.application.routes.draw do
  root 'general#welcome'
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }
  resources :acts
  get 'contracts/:id/details' => 'contracts#contract_detail'
  resources :contracts do
    resources :documents, only: [:new, :create, :edit, :update, :destroy, :show], as: :documents
  end
  get '/performances/list' => 'performances#performances_listing'
  resources :performances
  get 'performances/:id/details' => 'performances#performance_detail'
  scope 'admin' do
    resources :users, only: [:index, :edit, :update, :destroy]
  end

  resources :venues

  post 'approvals/approve' => 'approvals#approve', as: :contract_apvl_approve
  post 'approvals/reject' => 'approvals#reject', as: :contract_apvl_reject
  post 'approvals/cancel' => 'approvals#cancel', as: :contract_apvl_cancel
  get  'approvals/pending' => 'approvals#pending_approval'


end

app/views/layouts/_navigation.html.erb
<nav class="navbar-transparent navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %><strong>ems</strong><% end %>
    </div>
    <!-- Navigation Links -->
    <div class="collapse navbar-collapse">
      <% if current_user %>
      <ul class="nav navbar-nav">
        <li class="dropdown <%= 'active' if current_controller == "performances" %>">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= icon('music') %> Performances<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if policy(:performance).index? %><li><%= link_to 'List All My Performances', performances_path %></li><% end %>
            <% if policy(:performance).new? %><li><%= link_to 'Add Performance', new_performance_path %></li><% end %>
          </ul>
        </li>
        <li class="dropdown <%= 'active' if current_controller == "contracts" %>">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= icon('book') %> Contracts<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if policy(:contract).index? %><li><%= link_to 'List My Contracts', contracts_path %></li><% end %>
            <% if policy(:approval).pending_approval? %><li><%= link_to 'Pending Approvals', approvals_pending_path %></li><% end %>
          </ul>
        </li>
        <li class="dropdown <%= 'active' if current_controller == "acts" %>">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= icon('star') %> Acts<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if policy(:act).index? && current_user.role != 'act' %><li><%= link_to 'List All My Acts', acts_path %></li><% end %>
            <% if current_user.role == 'act' %><li><%= link_to 'My Act Details', act_path(current_user.try(:act_id)) %></li><% end %>
            <% if policy(:act).new? %><li><%= link_to 'Add Act', new_act_path %></li><% end %>
          </ul>
        </li>
        <li class="dropdown <%= 'active' if current_controller =="venues" %>">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= icon('map-marker') %> Venues<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if policy(:venue).index? && current_user.role != 'venue' %><li><%= link_to 'List My Venues', venues_path %></li><% end %>
            <% if current_user.role == 'venue' %><li><%= link_to 'My Venue Details', venue_path(current_user.try(:venue_id)) %></li><% end %>
            <% if policy(:venue).new? %><li><%= link_to 'Add Venue', new_venue_path %></li><% end %>
          </ul>
        </li>
        <% if policy(:user).edit? %><li class="<%= 'active' if current_controller == "users" %>"><%= link_to "#{icon('users')} Modify Users".html_safe, users_path %></li><% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown <%= 'active' if current_controller == "devise/registrations" %>">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= icon('user') %> Hi <%= current_user.name %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
      <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= 'active' if current_controller == "devise/registrations" %>"><%= link_to 'Register', new_user_registration_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= 'active' if current_controller == "devise/sessions" %>"><%= link_to 'Login', new_user_session_path %></li>
      </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<% %>
<html>
<head>
  <title>Entertainment Management System</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <style type="text/css">

  </style>
</head>
<body>
  <div id="SiteBody">
    <%= render 'layouts/navigation' %>

    <div class="container-fluid">
      <% if flash[:error] %>
      <p>&nbsp;</p>

      <div class="alert alert-danger" role="alert">
        <strong>ERROR:</strong> <%= flash[:error]  %>
      </div>
      <% end %>

      <% if flash[:alert] %>
      <p>&nbsp;</p>

      <div class="alert alert-warning" role="alert">
        <strong>ERROR:</strong> <%= flash[:alert]  %>
      </div>
      <% end %>

      <% if flash[:success] %>
      <p>&nbsp;</p>

      <div class="alert alert-success" role="alert">
        <strong>SUCCESS:</strong> <%= flash[:success]  %>
      </div>
      <% end %>
      <div class="row">
        <div class="col-sm-12">
          <div class="row">
            <div class="col-sm-offset-1 col-sm-8">
              <h1><%= "#{params[:controller].capitalize}" unless params[:controller].match(/general|devise/) %></h1>
            </div>
          </div>
          <div class="panel panel-default col-sm-offset-1 col-sm-10">
            <%= yield %>
            <br />
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12"></div>
    </div>

  </body>
  </html>